package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * AptitudCv generated by hbm2java
 */
public class AptitudCv  implements java.io.Serializable {


     private BigDecimal pkAptitudCv;
     private Cv cv;
     private CatalogoAptitud catalogoAptitud;

    public AptitudCv() {
    }

    public AptitudCv(BigDecimal pkAptitudCv, Cv cv, CatalogoAptitud catalogoAptitud) {
       this.pkAptitudCv = pkAptitudCv;
       this.cv = cv;
       this.catalogoAptitud = catalogoAptitud;
    }
   
    public BigDecimal getPkAptitudCv() {
        return this.pkAptitudCv;
    }
    
    public void setPkAptitudCv(BigDecimal pkAptitudCv) {
        this.pkAptitudCv = pkAptitudCv;
    }
    public Cv getCv() {
        return this.cv;
    }
    
    public void setCv(Cv cv) {
        this.cv = cv;
    }
    public CatalogoAptitud getCatalogoAptitud() {
        return this.catalogoAptitud;
    }
    
    public void setCatalogoAptitud(CatalogoAptitud catalogoAptitud) {
        this.catalogoAptitud = catalogoAptitud;
    }




}


