package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Candidato generated by hbm2java
 */
public class Candidato  implements java.io.Serializable {


     private BigDecimal pkCandidato;
     private CatalogoGenero catalogoGenero;
     private Municipio municipio;
     private String nombreCandidato;
     private String apellidoCandidato;
     private String nacionalidad;
     private int dui;
     private long nit;
     private Long nup;
     private Date fechaNacimiento;
     private String direccion;
     private Long telefono;
     private Long celular;
     private String facebook;
     private String twitter;
     private String pasaporte;
     private Blob fotoCandidato;
     private Set<Perfil> perfils = new HashSet<Perfil>(0);
     private Set<Cv> cvs = new HashSet<Cv>(0);

    public Candidato() {
    }

	
    public Candidato(BigDecimal pkCandidato, CatalogoGenero catalogoGenero, String nombreCandidato, String apellidoCandidato, String nacionalidad, int dui, long nit, Date fechaNacimiento, String direccion) {
        this.pkCandidato = pkCandidato;
        this.catalogoGenero = catalogoGenero;
        this.nombreCandidato = nombreCandidato;
        this.apellidoCandidato = apellidoCandidato;
        this.nacionalidad = nacionalidad;
        this.dui = dui;
        this.nit = nit;
        this.fechaNacimiento = fechaNacimiento;
        this.direccion = direccion;
    }
    public Candidato(BigDecimal pkCandidato, CatalogoGenero catalogoGenero, Municipio municipio, String nombreCandidato, String apellidoCandidato, String nacionalidad, int dui, long nit, Long nup, Date fechaNacimiento, String direccion, Long telefono, Long celular, String facebook, String twitter, String pasaporte, Blob fotoCandidato, Set<Perfil> perfils, Set<Cv> cvs) {
       this.pkCandidato = pkCandidato;
       this.catalogoGenero = catalogoGenero;
       this.municipio = municipio;
       this.nombreCandidato = nombreCandidato;
       this.apellidoCandidato = apellidoCandidato;
       this.nacionalidad = nacionalidad;
       this.dui = dui;
       this.nit = nit;
       this.nup = nup;
       this.fechaNacimiento = fechaNacimiento;
       this.direccion = direccion;
       this.telefono = telefono;
       this.celular = celular;
       this.facebook = facebook;
       this.twitter = twitter;
       this.pasaporte = pasaporte;
       this.fotoCandidato = fotoCandidato;
       this.perfils = perfils;
       this.cvs = cvs;
    }
   
    public BigDecimal getPkCandidato() {
        return this.pkCandidato;
    }
    
    public void setPkCandidato(BigDecimal pkCandidato) {
        this.pkCandidato = pkCandidato;
    }
    public CatalogoGenero getCatalogoGenero() {
        return this.catalogoGenero;
    }
    
    public void setCatalogoGenero(CatalogoGenero catalogoGenero) {
        this.catalogoGenero = catalogoGenero;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public String getNombreCandidato() {
        return this.nombreCandidato;
    }
    
    public void setNombreCandidato(String nombreCandidato) {
        this.nombreCandidato = nombreCandidato;
    }
    public String getApellidoCandidato() {
        return this.apellidoCandidato;
    }
    
    public void setApellidoCandidato(String apellidoCandidato) {
        this.apellidoCandidato = apellidoCandidato;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public int getDui() {
        return this.dui;
    }
    
    public void setDui(int dui) {
        this.dui = dui;
    }
    public long getNit() {
        return this.nit;
    }
    
    public void setNit(long nit) {
        this.nit = nit;
    }
    public Long getNup() {
        return this.nup;
    }
    
    public void setNup(Long nup) {
        this.nup = nup;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Long telefono) {
        this.telefono = telefono;
    }
    public Long getCelular() {
        return this.celular;
    }
    
    public void setCelular(Long celular) {
        this.celular = celular;
    }
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }
    public String getTwitter() {
        return this.twitter;
    }
    
    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }
    public String getPasaporte() {
        return this.pasaporte;
    }
    
    public void setPasaporte(String pasaporte) {
        this.pasaporte = pasaporte;
    }
    public Blob getFotoCandidato() {
        return this.fotoCandidato;
    }
    
    public void setFotoCandidato(Blob fotoCandidato) {
        this.fotoCandidato = fotoCandidato;
    }
    public Set<Perfil> getPerfils() {
        return this.perfils;
    }
    
    public void setPerfils(Set<Perfil> perfils) {
        this.perfils = perfils;
    }
    public Set<Cv> getCvs() {
        return this.cvs;
    }
    
    public void setCvs(Set<Cv> cvs) {
        this.cvs = cvs;
    }




}


