package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CatalogoTipoReferencia generated by hbm2java
 */
public class CatalogoTipoReferencia  implements java.io.Serializable {


     private BigDecimal pkTipoReferencia;
     private String tipoReferencia;
     private Set<Referencia> referencias = new HashSet<Referencia>(0);

    public CatalogoTipoReferencia() {
    }

	
    public CatalogoTipoReferencia(BigDecimal pkTipoReferencia, String tipoReferencia) {
        this.pkTipoReferencia = pkTipoReferencia;
        this.tipoReferencia = tipoReferencia;
    }
    public CatalogoTipoReferencia(BigDecimal pkTipoReferencia, String tipoReferencia, Set<Referencia> referencias) {
       this.pkTipoReferencia = pkTipoReferencia;
       this.tipoReferencia = tipoReferencia;
       this.referencias = referencias;
    }
   
    public BigDecimal getPkTipoReferencia() {
        return this.pkTipoReferencia;
    }
    
    public void setPkTipoReferencia(BigDecimal pkTipoReferencia) {
        this.pkTipoReferencia = pkTipoReferencia;
    }
    public String getTipoReferencia() {
        return this.tipoReferencia;
    }
    
    public void setTipoReferencia(String tipoReferencia) {
        this.tipoReferencia = tipoReferencia;
    }
    public Set<Referencia> getReferencias() {
        return this.referencias;
    }
    
    public void setReferencias(Set<Referencia> referencias) {
        this.referencias = referencias;
    }




}


