package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CatalogoGradoAcademico generated by hbm2java
 */
public class CatalogoGradoAcademico  implements java.io.Serializable {


     private BigDecimal pkGradoAcademico;
     private String nombreGradoAcademico;
     private Set<FormacionAcademica> formacionAcademicas = new HashSet<FormacionAcademica>(0);
     private Set<ConocimientoAcademicos> conocimientoAcademicoses = new HashSet<ConocimientoAcademicos>(0);

    public CatalogoGradoAcademico() {
    }

	
    public CatalogoGradoAcademico(BigDecimal pkGradoAcademico, String nombreGradoAcademico) {
        this.pkGradoAcademico = pkGradoAcademico;
        this.nombreGradoAcademico = nombreGradoAcademico;
    }
    public CatalogoGradoAcademico(BigDecimal pkGradoAcademico, String nombreGradoAcademico, Set<FormacionAcademica> formacionAcademicas, Set<ConocimientoAcademicos> conocimientoAcademicoses) {
       this.pkGradoAcademico = pkGradoAcademico;
       this.nombreGradoAcademico = nombreGradoAcademico;
       this.formacionAcademicas = formacionAcademicas;
       this.conocimientoAcademicoses = conocimientoAcademicoses;
    }
   
    public BigDecimal getPkGradoAcademico() {
        return this.pkGradoAcademico;
    }
    
    public void setPkGradoAcademico(BigDecimal pkGradoAcademico) {
        this.pkGradoAcademico = pkGradoAcademico;
    }
    public String getNombreGradoAcademico() {
        return this.nombreGradoAcademico;
    }
    
    public void setNombreGradoAcademico(String nombreGradoAcademico) {
        this.nombreGradoAcademico = nombreGradoAcademico;
    }
    public Set<FormacionAcademica> getFormacionAcademicas() {
        return this.formacionAcademicas;
    }
    
    public void setFormacionAcademicas(Set<FormacionAcademica> formacionAcademicas) {
        this.formacionAcademicas = formacionAcademicas;
    }
    public Set<ConocimientoAcademicos> getConocimientoAcademicoses() {
        return this.conocimientoAcademicoses;
    }
    
    public void setConocimientoAcademicoses(Set<ConocimientoAcademicos> conocimientoAcademicoses) {
        this.conocimientoAcademicoses = conocimientoAcademicoses;
    }




}


