package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CatalogoPonderacion generated by hbm2java
 */
public class CatalogoPonderacion  implements java.io.Serializable {


     private BigDecimal pkCatalogoPonderacion;
     private String etiquetaPonderacion;
     private String descripcionEtiqueta;
     private Set<HabilidadLinguisicaOferta> habilidadLinguisicaOfertas = new HashSet<HabilidadLinguisicaOferta>(0);
     private Set<HabilidadLinguisticaCv> habilidadLinguisticaCvs = new HashSet<HabilidadLinguisticaCv>(0);

    public CatalogoPonderacion() {
    }

	
    public CatalogoPonderacion(BigDecimal pkCatalogoPonderacion, String etiquetaPonderacion, String descripcionEtiqueta) {
        this.pkCatalogoPonderacion = pkCatalogoPonderacion;
        this.etiquetaPonderacion = etiquetaPonderacion;
        this.descripcionEtiqueta = descripcionEtiqueta;
    }
    public CatalogoPonderacion(BigDecimal pkCatalogoPonderacion, String etiquetaPonderacion, String descripcionEtiqueta, Set<HabilidadLinguisicaOferta> habilidadLinguisicaOfertas, Set<HabilidadLinguisticaCv> habilidadLinguisticaCvs) {
       this.pkCatalogoPonderacion = pkCatalogoPonderacion;
       this.etiquetaPonderacion = etiquetaPonderacion;
       this.descripcionEtiqueta = descripcionEtiqueta;
       this.habilidadLinguisicaOfertas = habilidadLinguisicaOfertas;
       this.habilidadLinguisticaCvs = habilidadLinguisticaCvs;
    }
   
    public BigDecimal getPkCatalogoPonderacion() {
        return this.pkCatalogoPonderacion;
    }
    
    public void setPkCatalogoPonderacion(BigDecimal pkCatalogoPonderacion) {
        this.pkCatalogoPonderacion = pkCatalogoPonderacion;
    }
    public String getEtiquetaPonderacion() {
        return this.etiquetaPonderacion;
    }
    
    public void setEtiquetaPonderacion(String etiquetaPonderacion) {
        this.etiquetaPonderacion = etiquetaPonderacion;
    }
    public String getDescripcionEtiqueta() {
        return this.descripcionEtiqueta;
    }
    
    public void setDescripcionEtiqueta(String descripcionEtiqueta) {
        this.descripcionEtiqueta = descripcionEtiqueta;
    }
    public Set<HabilidadLinguisicaOferta> getHabilidadLinguisicaOfertas() {
        return this.habilidadLinguisicaOfertas;
    }
    
    public void setHabilidadLinguisicaOfertas(Set<HabilidadLinguisicaOferta> habilidadLinguisicaOfertas) {
        this.habilidadLinguisicaOfertas = habilidadLinguisicaOfertas;
    }
    public Set<HabilidadLinguisticaCv> getHabilidadLinguisticaCvs() {
        return this.habilidadLinguisticaCvs;
    }
    
    public void setHabilidadLinguisticaCvs(Set<HabilidadLinguisticaCv> habilidadLinguisticaCvs) {
        this.habilidadLinguisticaCvs = habilidadLinguisticaCvs;
    }




}


