package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CatalogoTipoPrueba generated by hbm2java
 */
public class CatalogoTipoPrueba  implements java.io.Serializable {


     private BigDecimal pkCatTipoPrueba;
     private String nombreTipoPrueba;
     private Set<Prueba> pruebas = new HashSet<Prueba>(0);

    public CatalogoTipoPrueba() {
    }

	
    public CatalogoTipoPrueba(BigDecimal pkCatTipoPrueba, String nombreTipoPrueba) {
        this.pkCatTipoPrueba = pkCatTipoPrueba;
        this.nombreTipoPrueba = nombreTipoPrueba;
    }
    public CatalogoTipoPrueba(BigDecimal pkCatTipoPrueba, String nombreTipoPrueba, Set<Prueba> pruebas) {
       this.pkCatTipoPrueba = pkCatTipoPrueba;
       this.nombreTipoPrueba = nombreTipoPrueba;
       this.pruebas = pruebas;
    }
   
    public BigDecimal getPkCatTipoPrueba() {
        return this.pkCatTipoPrueba;
    }
    
    public void setPkCatTipoPrueba(BigDecimal pkCatTipoPrueba) {
        this.pkCatTipoPrueba = pkCatTipoPrueba;
    }
    public String getNombreTipoPrueba() {
        return this.nombreTipoPrueba;
    }
    
    public void setNombreTipoPrueba(String nombreTipoPrueba) {
        this.nombreTipoPrueba = nombreTipoPrueba;
    }
    public Set<Prueba> getPruebas() {
        return this.pruebas;
    }
    
    public void setPruebas(Set<Prueba> pruebas) {
        this.pruebas = pruebas;
    }




}


