package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CatalogoGenero generated by hbm2java
 */
public class CatalogoGenero  implements java.io.Serializable {


     private BigDecimal pkGenero;
     private String nombreGenero;
     private Set<Candidato> candidatos = new HashSet<Candidato>(0);

    public CatalogoGenero() {
    }

	
    public CatalogoGenero(BigDecimal pkGenero, String nombreGenero) {
        this.pkGenero = pkGenero;
        this.nombreGenero = nombreGenero;
    }
    public CatalogoGenero(BigDecimal pkGenero, String nombreGenero, Set<Candidato> candidatos) {
       this.pkGenero = pkGenero;
       this.nombreGenero = nombreGenero;
       this.candidatos = candidatos;
    }
   
    public BigDecimal getPkGenero() {
        return this.pkGenero;
    }
    
    public void setPkGenero(BigDecimal pkGenero) {
        this.pkGenero = pkGenero;
    }
    public String getNombreGenero() {
        return this.nombreGenero;
    }
    
    public void setNombreGenero(String nombreGenero) {
        this.nombreGenero = nombreGenero;
    }
    public Set<Candidato> getCandidatos() {
        return this.candidatos;
    }
    
    public void setCandidatos(Set<Candidato> candidatos) {
        this.candidatos = candidatos;
    }




}


