package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CatalogoSectorEmpresa generated by hbm2java
 */
public class CatalogoSectorEmpresa  implements java.io.Serializable {


     private BigDecimal pkSector;
     private String nombreSector;
     private Set<ExperienciaLaboral> experienciaLaborals = new HashSet<ExperienciaLaboral>(0);
     private Set<Empresa> empresas = new HashSet<Empresa>(0);

    public CatalogoSectorEmpresa() {
    }

	
    public CatalogoSectorEmpresa(BigDecimal pkSector, String nombreSector) {
        this.pkSector = pkSector;
        this.nombreSector = nombreSector;
    }
    public CatalogoSectorEmpresa(BigDecimal pkSector, String nombreSector, Set<ExperienciaLaboral> experienciaLaborals, Set<Empresa> empresas) {
       this.pkSector = pkSector;
       this.nombreSector = nombreSector;
       this.experienciaLaborals = experienciaLaborals;
       this.empresas = empresas;
    }
   
    public BigDecimal getPkSector() {
        return this.pkSector;
    }
    
    public void setPkSector(BigDecimal pkSector) {
        this.pkSector = pkSector;
    }
    public String getNombreSector() {
        return this.nombreSector;
    }
    
    public void setNombreSector(String nombreSector) {
        this.nombreSector = nombreSector;
    }
    public Set<ExperienciaLaboral> getExperienciaLaborals() {
        return this.experienciaLaborals;
    }
    
    public void setExperienciaLaborals(Set<ExperienciaLaboral> experienciaLaborals) {
        this.experienciaLaborals = experienciaLaborals;
    }
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }




}


