package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CatalogoCategoria generated by hbm2java
 */
public class CatalogoCategoria  implements java.io.Serializable {


     private BigDecimal pkCatalogoCategoria;
     private String nombreCatalogoCategoria;
     private Set<CatalogoPuesto> catalogoPuestos = new HashSet<CatalogoPuesto>(0);

    public CatalogoCategoria() {
    }

	
    public CatalogoCategoria(BigDecimal pkCatalogoCategoria, String nombreCatalogoCategoria) {
        this.pkCatalogoCategoria = pkCatalogoCategoria;
        this.nombreCatalogoCategoria = nombreCatalogoCategoria;
    }
    public CatalogoCategoria(BigDecimal pkCatalogoCategoria, String nombreCatalogoCategoria, Set<CatalogoPuesto> catalogoPuestos) {
       this.pkCatalogoCategoria = pkCatalogoCategoria;
       this.nombreCatalogoCategoria = nombreCatalogoCategoria;
       this.catalogoPuestos = catalogoPuestos;
    }
   
    public BigDecimal getPkCatalogoCategoria() {
        return this.pkCatalogoCategoria;
    }
    
    public void setPkCatalogoCategoria(BigDecimal pkCatalogoCategoria) {
        this.pkCatalogoCategoria = pkCatalogoCategoria;
    }
    public String getNombreCatalogoCategoria() {
        return this.nombreCatalogoCategoria;
    }
    
    public void setNombreCatalogoCategoria(String nombreCatalogoCategoria) {
        this.nombreCatalogoCategoria = nombreCatalogoCategoria;
    }
    public Set<CatalogoPuesto> getCatalogoPuestos() {
        return this.catalogoPuestos;
    }
    
    public void setCatalogoPuestos(Set<CatalogoPuesto> catalogoPuestos) {
        this.catalogoPuestos = catalogoPuestos;
    }




}


