package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CatalogoPuesto generated by hbm2java
 */
public class CatalogoPuesto  implements java.io.Serializable {


     private BigDecimal pkCatalogoPuesto;
     private CatalogoCategoria catalogoCategoria;
     private String nombreCatalogoPuesto;
     private Set<Oferta> ofertas = new HashSet<Oferta>(0);

    public CatalogoPuesto() {
    }

	
    public CatalogoPuesto(BigDecimal pkCatalogoPuesto, CatalogoCategoria catalogoCategoria, String nombreCatalogoPuesto) {
        this.pkCatalogoPuesto = pkCatalogoPuesto;
        this.catalogoCategoria = catalogoCategoria;
        this.nombreCatalogoPuesto = nombreCatalogoPuesto;
    }
    public CatalogoPuesto(BigDecimal pkCatalogoPuesto, CatalogoCategoria catalogoCategoria, String nombreCatalogoPuesto, Set<Oferta> ofertas) {
       this.pkCatalogoPuesto = pkCatalogoPuesto;
       this.catalogoCategoria = catalogoCategoria;
       this.nombreCatalogoPuesto = nombreCatalogoPuesto;
       this.ofertas = ofertas;
    }
   
    public BigDecimal getPkCatalogoPuesto() {
        return this.pkCatalogoPuesto;
    }
    
    public void setPkCatalogoPuesto(BigDecimal pkCatalogoPuesto) {
        this.pkCatalogoPuesto = pkCatalogoPuesto;
    }
    public CatalogoCategoria getCatalogoCategoria() {
        return this.catalogoCategoria;
    }
    
    public void setCatalogoCategoria(CatalogoCategoria catalogoCategoria) {
        this.catalogoCategoria = catalogoCategoria;
    }
    public String getNombreCatalogoPuesto() {
        return this.nombreCatalogoPuesto;
    }
    
    public void setNombreCatalogoPuesto(String nombreCatalogoPuesto) {
        this.nombreCatalogoPuesto = nombreCatalogoPuesto;
    }
    public Set<Oferta> getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Set<Oferta> ofertas) {
        this.ofertas = ofertas;
    }




}


