package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CatalogoEscrito generated by hbm2java
 */
public class CatalogoEscrito  implements java.io.Serializable {


     private BigDecimal pkCatalogoEscrito;
     private String nombreTipoEscrito;
     private Set<Escrito> escritos = new HashSet<Escrito>(0);

    public CatalogoEscrito() {
    }

	
    public CatalogoEscrito(BigDecimal pkCatalogoEscrito, String nombreTipoEscrito) {
        this.pkCatalogoEscrito = pkCatalogoEscrito;
        this.nombreTipoEscrito = nombreTipoEscrito;
    }
    public CatalogoEscrito(BigDecimal pkCatalogoEscrito, String nombreTipoEscrito, Set<Escrito> escritos) {
       this.pkCatalogoEscrito = pkCatalogoEscrito;
       this.nombreTipoEscrito = nombreTipoEscrito;
       this.escritos = escritos;
    }
   
    public BigDecimal getPkCatalogoEscrito() {
        return this.pkCatalogoEscrito;
    }
    
    public void setPkCatalogoEscrito(BigDecimal pkCatalogoEscrito) {
        this.pkCatalogoEscrito = pkCatalogoEscrito;
    }
    public String getNombreTipoEscrito() {
        return this.nombreTipoEscrito;
    }
    
    public void setNombreTipoEscrito(String nombreTipoEscrito) {
        this.nombreTipoEscrito = nombreTipoEscrito;
    }
    public Set<Escrito> getEscritos() {
        return this.escritos;
    }
    
    public void setEscritos(Set<Escrito> escritos) {
        this.escritos = escritos;
    }




}


