package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CatalogoCategoriaHabilidad generated by hbm2java
 */
public class CatalogoCategoriaHabilidad  implements java.io.Serializable {


     private BigDecimal pkCategoriaHabilidad;
     private String nombreCategoriaHabilidad;
     private Set<CatalogoHabilidad> catalogoHabilidads = new HashSet<CatalogoHabilidad>(0);

    public CatalogoCategoriaHabilidad() {
    }

	
    public CatalogoCategoriaHabilidad(BigDecimal pkCategoriaHabilidad, String nombreCategoriaHabilidad) {
        this.pkCategoriaHabilidad = pkCategoriaHabilidad;
        this.nombreCategoriaHabilidad = nombreCategoriaHabilidad;
    }
    public CatalogoCategoriaHabilidad(BigDecimal pkCategoriaHabilidad, String nombreCategoriaHabilidad, Set<CatalogoHabilidad> catalogoHabilidads) {
       this.pkCategoriaHabilidad = pkCategoriaHabilidad;
       this.nombreCategoriaHabilidad = nombreCategoriaHabilidad;
       this.catalogoHabilidads = catalogoHabilidads;
    }
   
    public BigDecimal getPkCategoriaHabilidad() {
        return this.pkCategoriaHabilidad;
    }
    
    public void setPkCategoriaHabilidad(BigDecimal pkCategoriaHabilidad) {
        this.pkCategoriaHabilidad = pkCategoriaHabilidad;
    }
    public String getNombreCategoriaHabilidad() {
        return this.nombreCategoriaHabilidad;
    }
    
    public void setNombreCategoriaHabilidad(String nombreCategoriaHabilidad) {
        this.nombreCategoriaHabilidad = nombreCategoriaHabilidad;
    }
    public Set<CatalogoHabilidad> getCatalogoHabilidads() {
        return this.catalogoHabilidads;
    }
    
    public void setCatalogoHabilidads(Set<CatalogoHabilidad> catalogoHabilidads) {
        this.catalogoHabilidads = catalogoHabilidads;
    }




}


