package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CatalogoHabilidad generated by hbm2java
 */
public class CatalogoHabilidad  implements java.io.Serializable {


     private BigDecimal pkHabilidad;
     private CatalogoCategoriaHabilidad catalogoCategoriaHabilidad;
     private String nombreHabilidad;
     private Set<HabilidadOferta> habilidadOfertas = new HashSet<HabilidadOferta>(0);
     private Set<HabilidadesCv> habilidadesCvs = new HashSet<HabilidadesCv>(0);

    public CatalogoHabilidad() {
    }

	
    public CatalogoHabilidad(BigDecimal pkHabilidad, CatalogoCategoriaHabilidad catalogoCategoriaHabilidad, String nombreHabilidad) {
        this.pkHabilidad = pkHabilidad;
        this.catalogoCategoriaHabilidad = catalogoCategoriaHabilidad;
        this.nombreHabilidad = nombreHabilidad;
    }
    public CatalogoHabilidad(BigDecimal pkHabilidad, CatalogoCategoriaHabilidad catalogoCategoriaHabilidad, String nombreHabilidad, Set<HabilidadOferta> habilidadOfertas, Set<HabilidadesCv> habilidadesCvs) {
       this.pkHabilidad = pkHabilidad;
       this.catalogoCategoriaHabilidad = catalogoCategoriaHabilidad;
       this.nombreHabilidad = nombreHabilidad;
       this.habilidadOfertas = habilidadOfertas;
       this.habilidadesCvs = habilidadesCvs;
    }
   
    public BigDecimal getPkHabilidad() {
        return this.pkHabilidad;
    }
    
    public void setPkHabilidad(BigDecimal pkHabilidad) {
        this.pkHabilidad = pkHabilidad;
    }
    public CatalogoCategoriaHabilidad getCatalogoCategoriaHabilidad() {
        return this.catalogoCategoriaHabilidad;
    }
    
    public void setCatalogoCategoriaHabilidad(CatalogoCategoriaHabilidad catalogoCategoriaHabilidad) {
        this.catalogoCategoriaHabilidad = catalogoCategoriaHabilidad;
    }
    public String getNombreHabilidad() {
        return this.nombreHabilidad;
    }
    
    public void setNombreHabilidad(String nombreHabilidad) {
        this.nombreHabilidad = nombreHabilidad;
    }
    public Set<HabilidadOferta> getHabilidadOfertas() {
        return this.habilidadOfertas;
    }
    
    public void setHabilidadOfertas(Set<HabilidadOferta> habilidadOfertas) {
        this.habilidadOfertas = habilidadOfertas;
    }
    public Set<HabilidadesCv> getHabilidadesCvs() {
        return this.habilidadesCvs;
    }
    
    public void setHabilidadesCvs(Set<HabilidadesCv> habilidadesCvs) {
        this.habilidadesCvs = habilidadesCvs;
    }




}


