package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ConocimientoAcademicos generated by hbm2java
 */
public class ConocimientoAcademicos  implements java.io.Serializable {


     private BigDecimal pkConocimientoAcademico;
     private CatalogoGradoAcademico catalogoGradoAcademico;
     private Oferta oferta;

    public ConocimientoAcademicos() {
    }

    public ConocimientoAcademicos(BigDecimal pkConocimientoAcademico, CatalogoGradoAcademico catalogoGradoAcademico, Oferta oferta) {
       this.pkConocimientoAcademico = pkConocimientoAcademico;
       this.catalogoGradoAcademico = catalogoGradoAcademico;
       this.oferta = oferta;
    }
   
    public BigDecimal getPkConocimientoAcademico() {
        return this.pkConocimientoAcademico;
    }
    
    public void setPkConocimientoAcademico(BigDecimal pkConocimientoAcademico) {
        this.pkConocimientoAcademico = pkConocimientoAcademico;
    }
    public CatalogoGradoAcademico getCatalogoGradoAcademico() {
        return this.catalogoGradoAcademico;
    }
    
    public void setCatalogoGradoAcademico(CatalogoGradoAcademico catalogoGradoAcademico) {
        this.catalogoGradoAcademico = catalogoGradoAcademico;
    }
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }




}


