package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CursoCapacitacion generated by hbm2java
 */
public class CursoCapacitacion  implements java.io.Serializable {


     private BigDecimal pkCursoCapacitacion;
     private Cv cv;
     private String nombreCursoCapacitacion;
     private Date fechaCurso;
     private String nombreInstitutoPonente;
     private String duracion;
     private String lugarCapacitacion;

    public CursoCapacitacion() {
    }

	
    public CursoCapacitacion(BigDecimal pkCursoCapacitacion, Cv cv, String nombreCursoCapacitacion, Date fechaCurso, String nombreInstitutoPonente, String lugarCapacitacion) {
        this.pkCursoCapacitacion = pkCursoCapacitacion;
        this.cv = cv;
        this.nombreCursoCapacitacion = nombreCursoCapacitacion;
        this.fechaCurso = fechaCurso;
        this.nombreInstitutoPonente = nombreInstitutoPonente;
        this.lugarCapacitacion = lugarCapacitacion;
    }
    public CursoCapacitacion(BigDecimal pkCursoCapacitacion, Cv cv, String nombreCursoCapacitacion, Date fechaCurso, String nombreInstitutoPonente, String duracion, String lugarCapacitacion) {
       this.pkCursoCapacitacion = pkCursoCapacitacion;
       this.cv = cv;
       this.nombreCursoCapacitacion = nombreCursoCapacitacion;
       this.fechaCurso = fechaCurso;
       this.nombreInstitutoPonente = nombreInstitutoPonente;
       this.duracion = duracion;
       this.lugarCapacitacion = lugarCapacitacion;
    }
   
    public BigDecimal getPkCursoCapacitacion() {
        return this.pkCursoCapacitacion;
    }
    
    public void setPkCursoCapacitacion(BigDecimal pkCursoCapacitacion) {
        this.pkCursoCapacitacion = pkCursoCapacitacion;
    }
    public Cv getCv() {
        return this.cv;
    }
    
    public void setCv(Cv cv) {
        this.cv = cv;
    }
    public String getNombreCursoCapacitacion() {
        return this.nombreCursoCapacitacion;
    }
    
    public void setNombreCursoCapacitacion(String nombreCursoCapacitacion) {
        this.nombreCursoCapacitacion = nombreCursoCapacitacion;
    }
    public Date getFechaCurso() {
        return this.fechaCurso;
    }
    
    public void setFechaCurso(Date fechaCurso) {
        this.fechaCurso = fechaCurso;
    }
    public String getNombreInstitutoPonente() {
        return this.nombreInstitutoPonente;
    }
    
    public void setNombreInstitutoPonente(String nombreInstitutoPonente) {
        this.nombreInstitutoPonente = nombreInstitutoPonente;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public String getLugarCapacitacion() {
        return this.lugarCapacitacion;
    }
    
    public void setLugarCapacitacion(String lugarCapacitacion) {
        this.lugarCapacitacion = lugarCapacitacion;
    }




}


