package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cv generated by hbm2java
 */
public class Cv  implements java.io.Serializable {


     private BigDecimal pkCv;
     private Candidato candidato;
     private String nombreCv;
     private Date fechaRegistro;
     private Date fechaActualizado;
     private Set<LicenciaCandidato> licenciaCandidatos = new HashSet<LicenciaCandidato>(0);
     private Set<CursoCapacitacion> cursoCapacitacions = new HashSet<CursoCapacitacion>(0);
     private Set<Logro> logros = new HashSet<Logro>(0);
     private Set<Evento> eventos = new HashSet<Evento>(0);
     private Set<ExperienciaLaboral> experienciaLaborals = new HashSet<ExperienciaLaboral>(0);
     private Set<Postulacion> postulacions = new HashSet<Postulacion>(0);
     private Set<Referencia> referencias = new HashSet<Referencia>(0);
     private Set<HabilidadLinguisticaCv> habilidadLinguisticaCvs = new HashSet<HabilidadLinguisticaCv>(0);
     private Set<Escrito> escritos = new HashSet<Escrito>(0);
     private Set<FormacionAcademica> formacionAcademicas = new HashSet<FormacionAcademica>(0);
     private Set<HabilidadesCv> habilidadesCvs = new HashSet<HabilidadesCv>(0);
     private Set<AptitudCv> aptitudCvs = new HashSet<AptitudCv>(0);

    public Cv() {
    }

	
    public Cv(BigDecimal pkCv, Candidato candidato, String nombreCv, Date fechaRegistro, Date fechaActualizado) {
        this.pkCv = pkCv;
        this.candidato = candidato;
        this.nombreCv = nombreCv;
        this.fechaRegistro = fechaRegistro;
        this.fechaActualizado = fechaActualizado;
    }
    public Cv(BigDecimal pkCv, Candidato candidato, String nombreCv, Date fechaRegistro, Date fechaActualizado, Set<LicenciaCandidato> licenciaCandidatos, Set<CursoCapacitacion> cursoCapacitacions, Set<Logro> logros, Set<Evento> eventos, Set<ExperienciaLaboral> experienciaLaborals, Set<Postulacion> postulacions, Set<Referencia> referencias, Set<HabilidadLinguisticaCv> habilidadLinguisticaCvs, Set<Escrito> escritos, Set<FormacionAcademica> formacionAcademicas, Set<HabilidadesCv> habilidadesCvs, Set<AptitudCv> aptitudCvs) {
       this.pkCv = pkCv;
       this.candidato = candidato;
       this.nombreCv = nombreCv;
       this.fechaRegistro = fechaRegistro;
       this.fechaActualizado = fechaActualizado;
       this.licenciaCandidatos = licenciaCandidatos;
       this.cursoCapacitacions = cursoCapacitacions;
       this.logros = logros;
       this.eventos = eventos;
       this.experienciaLaborals = experienciaLaborals;
       this.postulacions = postulacions;
       this.referencias = referencias;
       this.habilidadLinguisticaCvs = habilidadLinguisticaCvs;
       this.escritos = escritos;
       this.formacionAcademicas = formacionAcademicas;
       this.habilidadesCvs = habilidadesCvs;
       this.aptitudCvs = aptitudCvs;
    }
   
    public BigDecimal getPkCv() {
        return this.pkCv;
    }
    
    public void setPkCv(BigDecimal pkCv) {
        this.pkCv = pkCv;
    }
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }
    public String getNombreCv() {
        return this.nombreCv;
    }
    
    public void setNombreCv(String nombreCv) {
        this.nombreCv = nombreCv;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaActualizado() {
        return this.fechaActualizado;
    }
    
    public void setFechaActualizado(Date fechaActualizado) {
        this.fechaActualizado = fechaActualizado;
    }
    public Set<LicenciaCandidato> getLicenciaCandidatos() {
        return this.licenciaCandidatos;
    }
    
    public void setLicenciaCandidatos(Set<LicenciaCandidato> licenciaCandidatos) {
        this.licenciaCandidatos = licenciaCandidatos;
    }
    public Set<CursoCapacitacion> getCursoCapacitacions() {
        return this.cursoCapacitacions;
    }
    
    public void setCursoCapacitacions(Set<CursoCapacitacion> cursoCapacitacions) {
        this.cursoCapacitacions = cursoCapacitacions;
    }
    public Set<Logro> getLogros() {
        return this.logros;
    }
    
    public void setLogros(Set<Logro> logros) {
        this.logros = logros;
    }
    public Set<Evento> getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set<Evento> eventos) {
        this.eventos = eventos;
    }
    public Set<ExperienciaLaboral> getExperienciaLaborals() {
        return this.experienciaLaborals;
    }
    
    public void setExperienciaLaborals(Set<ExperienciaLaboral> experienciaLaborals) {
        this.experienciaLaborals = experienciaLaborals;
    }
    public Set<Postulacion> getPostulacions() {
        return this.postulacions;
    }
    
    public void setPostulacions(Set<Postulacion> postulacions) {
        this.postulacions = postulacions;
    }
    public Set<Referencia> getReferencias() {
        return this.referencias;
    }
    
    public void setReferencias(Set<Referencia> referencias) {
        this.referencias = referencias;
    }
    public Set<HabilidadLinguisticaCv> getHabilidadLinguisticaCvs() {
        return this.habilidadLinguisticaCvs;
    }
    
    public void setHabilidadLinguisticaCvs(Set<HabilidadLinguisticaCv> habilidadLinguisticaCvs) {
        this.habilidadLinguisticaCvs = habilidadLinguisticaCvs;
    }
    public Set<Escrito> getEscritos() {
        return this.escritos;
    }
    
    public void setEscritos(Set<Escrito> escritos) {
        this.escritos = escritos;
    }
    public Set<FormacionAcademica> getFormacionAcademicas() {
        return this.formacionAcademicas;
    }
    
    public void setFormacionAcademicas(Set<FormacionAcademica> formacionAcademicas) {
        this.formacionAcademicas = formacionAcademicas;
    }
    public Set<HabilidadesCv> getHabilidadesCvs() {
        return this.habilidadesCvs;
    }
    
    public void setHabilidadesCvs(Set<HabilidadesCv> habilidadesCvs) {
        this.habilidadesCvs = habilidadesCvs;
    }
    public Set<AptitudCv> getAptitudCvs() {
        return this.aptitudCvs;
    }
    
    public void setAptitudCvs(Set<AptitudCv> aptitudCvs) {
        this.aptitudCvs = aptitudCvs;
    }




}


