package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private BigDecimal pkDepartamento;
     private Pais pais;
     private String nombreDepartamento;
     private Set<Municipio> municipios = new HashSet<Municipio>(0);

    public Departamento() {
    }

	
    public Departamento(BigDecimal pkDepartamento, String nombreDepartamento) {
        this.pkDepartamento = pkDepartamento;
        this.nombreDepartamento = nombreDepartamento;
    }
    public Departamento(BigDecimal pkDepartamento, Pais pais, String nombreDepartamento, Set<Municipio> municipios) {
       this.pkDepartamento = pkDepartamento;
       this.pais = pais;
       this.nombreDepartamento = nombreDepartamento;
       this.municipios = municipios;
    }
   
    public BigDecimal getPkDepartamento() {
        return this.pkDepartamento;
    }
    
    public void setPkDepartamento(BigDecimal pkDepartamento) {
        this.pkDepartamento = pkDepartamento;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public Set<Municipio> getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Set<Municipio> municipios) {
        this.municipios = municipios;
    }




}


