package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private BigDecimal pkEmpresa;
     private CatalogoSectorEmpresa catalogoSectorEmpresa;
     private CatalogoTipoEmpresa catalogoTipoEmpresa;
     private Municipio municipio;
     private String nomEmpresa;
     private long nitEmpresa;
     private String direccionEmpresa;
     private String razonSocial;
     private BigDecimal numeroTrabajadores;
     private String descripcionEmpresa;
     private String paginaWeb;
     private Blob logoEmpresa;
     private String nombreContactoEmpresa;
     private String cargoContacto;
     private BigDecimal telefonoContacto;
     private Set<Oferta> ofertas = new HashSet<Oferta>(0);
     private Set<Perfil> perfils = new HashSet<Perfil>(0);

    public Empresa() {
    }

	
    public Empresa(BigDecimal pkEmpresa, CatalogoSectorEmpresa catalogoSectorEmpresa, CatalogoTipoEmpresa catalogoTipoEmpresa, String nomEmpresa, long nitEmpresa, String direccionEmpresa, String razonSocial, String descripcionEmpresa, String nombreContactoEmpresa, BigDecimal telefonoContacto) {
        this.pkEmpresa = pkEmpresa;
        this.catalogoSectorEmpresa = catalogoSectorEmpresa;
        this.catalogoTipoEmpresa = catalogoTipoEmpresa;
        this.nomEmpresa = nomEmpresa;
        this.nitEmpresa = nitEmpresa;
        this.direccionEmpresa = direccionEmpresa;
        this.razonSocial = razonSocial;
        this.descripcionEmpresa = descripcionEmpresa;
        this.nombreContactoEmpresa = nombreContactoEmpresa;
        this.telefonoContacto = telefonoContacto;
    }
    public Empresa(BigDecimal pkEmpresa, CatalogoSectorEmpresa catalogoSectorEmpresa, CatalogoTipoEmpresa catalogoTipoEmpresa, Municipio municipio, String nomEmpresa, long nitEmpresa, String direccionEmpresa, String razonSocial, BigDecimal numeroTrabajadores, String descripcionEmpresa, String paginaWeb, Blob logoEmpresa, String nombreContactoEmpresa, String cargoContacto, BigDecimal telefonoContacto, Set<Oferta> ofertas, Set<Perfil> perfils) {
       this.pkEmpresa = pkEmpresa;
       this.catalogoSectorEmpresa = catalogoSectorEmpresa;
       this.catalogoTipoEmpresa = catalogoTipoEmpresa;
       this.municipio = municipio;
       this.nomEmpresa = nomEmpresa;
       this.nitEmpresa = nitEmpresa;
       this.direccionEmpresa = direccionEmpresa;
       this.razonSocial = razonSocial;
       this.numeroTrabajadores = numeroTrabajadores;
       this.descripcionEmpresa = descripcionEmpresa;
       this.paginaWeb = paginaWeb;
       this.logoEmpresa = logoEmpresa;
       this.nombreContactoEmpresa = nombreContactoEmpresa;
       this.cargoContacto = cargoContacto;
       this.telefonoContacto = telefonoContacto;
       this.ofertas = ofertas;
       this.perfils = perfils;
    }
   
    public BigDecimal getPkEmpresa() {
        return this.pkEmpresa;
    }
    
    public void setPkEmpresa(BigDecimal pkEmpresa) {
        this.pkEmpresa = pkEmpresa;
    }
    public CatalogoSectorEmpresa getCatalogoSectorEmpresa() {
        return this.catalogoSectorEmpresa;
    }
    
    public void setCatalogoSectorEmpresa(CatalogoSectorEmpresa catalogoSectorEmpresa) {
        this.catalogoSectorEmpresa = catalogoSectorEmpresa;
    }
    public CatalogoTipoEmpresa getCatalogoTipoEmpresa() {
        return this.catalogoTipoEmpresa;
    }
    
    public void setCatalogoTipoEmpresa(CatalogoTipoEmpresa catalogoTipoEmpresa) {
        this.catalogoTipoEmpresa = catalogoTipoEmpresa;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public String getNomEmpresa() {
        return this.nomEmpresa;
    }
    
    public void setNomEmpresa(String nomEmpresa) {
        this.nomEmpresa = nomEmpresa;
    }
    public long getNitEmpresa() {
        return this.nitEmpresa;
    }
    
    public void setNitEmpresa(long nitEmpresa) {
        this.nitEmpresa = nitEmpresa;
    }
    public String getDireccionEmpresa() {
        return this.direccionEmpresa;
    }
    
    public void setDireccionEmpresa(String direccionEmpresa) {
        this.direccionEmpresa = direccionEmpresa;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public BigDecimal getNumeroTrabajadores() {
        return this.numeroTrabajadores;
    }
    
    public void setNumeroTrabajadores(BigDecimal numeroTrabajadores) {
        this.numeroTrabajadores = numeroTrabajadores;
    }
    public String getDescripcionEmpresa() {
        return this.descripcionEmpresa;
    }
    
    public void setDescripcionEmpresa(String descripcionEmpresa) {
        this.descripcionEmpresa = descripcionEmpresa;
    }
    public String getPaginaWeb() {
        return this.paginaWeb;
    }
    
    public void setPaginaWeb(String paginaWeb) {
        this.paginaWeb = paginaWeb;
    }
    public Blob getLogoEmpresa() {
        return this.logoEmpresa;
    }
    
    public void setLogoEmpresa(Blob logoEmpresa) {
        this.logoEmpresa = logoEmpresa;
    }
    public String getNombreContactoEmpresa() {
        return this.nombreContactoEmpresa;
    }
    
    public void setNombreContactoEmpresa(String nombreContactoEmpresa) {
        this.nombreContactoEmpresa = nombreContactoEmpresa;
    }
    public String getCargoContacto() {
        return this.cargoContacto;
    }
    
    public void setCargoContacto(String cargoContacto) {
        this.cargoContacto = cargoContacto;
    }
    public BigDecimal getTelefonoContacto() {
        return this.telefonoContacto;
    }
    
    public void setTelefonoContacto(BigDecimal telefonoContacto) {
        this.telefonoContacto = telefonoContacto;
    }
    public Set<Oferta> getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Set<Oferta> ofertas) {
        this.ofertas = ofertas;
    }
    public Set<Perfil> getPerfils() {
        return this.perfils;
    }
    
    public void setPerfils(Set<Perfil> perfils) {
        this.perfils = perfils;
    }




}


