package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Escrito generated by hbm2java
 */
public class Escrito  implements java.io.Serializable {


     private BigDecimal pkEscrito;
     private Cv cv;
     private CatalogoEscrito catalogoEscrito;
     private Date fechaPublicacion;
     private String lugarPublicacion;
     private String nombreEditor;
     private String nombreEscrito;

    public Escrito() {
    }

    public Escrito(BigDecimal pkEscrito, Cv cv, CatalogoEscrito catalogoEscrito, Date fechaPublicacion, String lugarPublicacion, String nombreEditor, String nombreEscrito) {
       this.pkEscrito = pkEscrito;
       this.cv = cv;
       this.catalogoEscrito = catalogoEscrito;
       this.fechaPublicacion = fechaPublicacion;
       this.lugarPublicacion = lugarPublicacion;
       this.nombreEditor = nombreEditor;
       this.nombreEscrito = nombreEscrito;
    }
   
    public BigDecimal getPkEscrito() {
        return this.pkEscrito;
    }
    
    public void setPkEscrito(BigDecimal pkEscrito) {
        this.pkEscrito = pkEscrito;
    }
    public Cv getCv() {
        return this.cv;
    }
    
    public void setCv(Cv cv) {
        this.cv = cv;
    }
    public CatalogoEscrito getCatalogoEscrito() {
        return this.catalogoEscrito;
    }
    
    public void setCatalogoEscrito(CatalogoEscrito catalogoEscrito) {
        this.catalogoEscrito = catalogoEscrito;
    }
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }
    public String getLugarPublicacion() {
        return this.lugarPublicacion;
    }
    
    public void setLugarPublicacion(String lugarPublicacion) {
        this.lugarPublicacion = lugarPublicacion;
    }
    public String getNombreEditor() {
        return this.nombreEditor;
    }
    
    public void setNombreEditor(String nombreEditor) {
        this.nombreEditor = nombreEditor;
    }
    public String getNombreEscrito() {
        return this.nombreEscrito;
    }
    
    public void setNombreEscrito(String nombreEscrito) {
        this.nombreEscrito = nombreEscrito;
    }




}


