package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private BigDecimal pkEvento;
     private Cv cv;
     private Pais pais;
     private String nombreEvento;
     private String descripcionEvento;
     private String lugarEvento;
     private String anfitrionEvento;
     private Date fechaEvento;

    public Evento() {
    }

    public Evento(BigDecimal pkEvento, Cv cv, Pais pais, String nombreEvento, String descripcionEvento, String lugarEvento, String anfitrionEvento, Date fechaEvento) {
       this.pkEvento = pkEvento;
       this.cv = cv;
       this.pais = pais;
       this.nombreEvento = nombreEvento;
       this.descripcionEvento = descripcionEvento;
       this.lugarEvento = lugarEvento;
       this.anfitrionEvento = anfitrionEvento;
       this.fechaEvento = fechaEvento;
    }
   
    public BigDecimal getPkEvento() {
        return this.pkEvento;
    }
    
    public void setPkEvento(BigDecimal pkEvento) {
        this.pkEvento = pkEvento;
    }
    public Cv getCv() {
        return this.cv;
    }
    
    public void setCv(Cv cv) {
        this.cv = cv;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNombreEvento() {
        return this.nombreEvento;
    }
    
    public void setNombreEvento(String nombreEvento) {
        this.nombreEvento = nombreEvento;
    }
    public String getDescripcionEvento() {
        return this.descripcionEvento;
    }
    
    public void setDescripcionEvento(String descripcionEvento) {
        this.descripcionEvento = descripcionEvento;
    }
    public String getLugarEvento() {
        return this.lugarEvento;
    }
    
    public void setLugarEvento(String lugarEvento) {
        this.lugarEvento = lugarEvento;
    }
    public String getAnfitrionEvento() {
        return this.anfitrionEvento;
    }
    
    public void setAnfitrionEvento(String anfitrionEvento) {
        this.anfitrionEvento = anfitrionEvento;
    }
    public Date getFechaEvento() {
        return this.fechaEvento;
    }
    
    public void setFechaEvento(Date fechaEvento) {
        this.fechaEvento = fechaEvento;
    }




}


