package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * FormacionAcademica generated by hbm2java
 */
public class FormacionAcademica  implements java.io.Serializable {


     private BigDecimal pkFormacionAcademica;
     private Cv cv;
     private CatalogoGradoAcademico catalogoGradoAcademico;
     private String nombreInstitucion;
     private Date anoInicio;
     private Date anoFin;
     private String nombreTitulo;
     private BigDecimal enCurso;

    public FormacionAcademica() {
    }

	
    public FormacionAcademica(BigDecimal pkFormacionAcademica, Cv cv, CatalogoGradoAcademico catalogoGradoAcademico, String nombreInstitucion, Date anoInicio, String nombreTitulo) {
        this.pkFormacionAcademica = pkFormacionAcademica;
        this.cv = cv;
        this.catalogoGradoAcademico = catalogoGradoAcademico;
        this.nombreInstitucion = nombreInstitucion;
        this.anoInicio = anoInicio;
        this.nombreTitulo = nombreTitulo;
    }
    public FormacionAcademica(BigDecimal pkFormacionAcademica, Cv cv, CatalogoGradoAcademico catalogoGradoAcademico, String nombreInstitucion, Date anoInicio, Date anoFin, String nombreTitulo, BigDecimal enCurso) {
       this.pkFormacionAcademica = pkFormacionAcademica;
       this.cv = cv;
       this.catalogoGradoAcademico = catalogoGradoAcademico;
       this.nombreInstitucion = nombreInstitucion;
       this.anoInicio = anoInicio;
       this.anoFin = anoFin;
       this.nombreTitulo = nombreTitulo;
       this.enCurso = enCurso;
    }
   
    public BigDecimal getPkFormacionAcademica() {
        return this.pkFormacionAcademica;
    }
    
    public void setPkFormacionAcademica(BigDecimal pkFormacionAcademica) {
        this.pkFormacionAcademica = pkFormacionAcademica;
    }
    public Cv getCv() {
        return this.cv;
    }
    
    public void setCv(Cv cv) {
        this.cv = cv;
    }
    public CatalogoGradoAcademico getCatalogoGradoAcademico() {
        return this.catalogoGradoAcademico;
    }
    
    public void setCatalogoGradoAcademico(CatalogoGradoAcademico catalogoGradoAcademico) {
        this.catalogoGradoAcademico = catalogoGradoAcademico;
    }
    public String getNombreInstitucion() {
        return this.nombreInstitucion;
    }
    
    public void setNombreInstitucion(String nombreInstitucion) {
        this.nombreInstitucion = nombreInstitucion;
    }
    public Date getAnoInicio() {
        return this.anoInicio;
    }
    
    public void setAnoInicio(Date anoInicio) {
        this.anoInicio = anoInicio;
    }
    public Date getAnoFin() {
        return this.anoFin;
    }
    
    public void setAnoFin(Date anoFin) {
        this.anoFin = anoFin;
    }
    public String getNombreTitulo() {
        return this.nombreTitulo;
    }
    
    public void setNombreTitulo(String nombreTitulo) {
        this.nombreTitulo = nombreTitulo;
    }
    public BigDecimal getEnCurso() {
        return this.enCurso;
    }
    
    public void setEnCurso(BigDecimal enCurso) {
        this.enCurso = enCurso;
    }




}


