package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * HabilidadesCv generated by hbm2java
 */
public class HabilidadesCv  implements java.io.Serializable {


     private BigDecimal pkHabilidadesCv;
     private Cv cv;
     private CatalogoHabilidad catalogoHabilidad;

    public HabilidadesCv() {
    }

    public HabilidadesCv(BigDecimal pkHabilidadesCv, Cv cv, CatalogoHabilidad catalogoHabilidad) {
       this.pkHabilidadesCv = pkHabilidadesCv;
       this.cv = cv;
       this.catalogoHabilidad = catalogoHabilidad;
    }
   
    public BigDecimal getPkHabilidadesCv() {
        return this.pkHabilidadesCv;
    }
    
    public void setPkHabilidadesCv(BigDecimal pkHabilidadesCv) {
        this.pkHabilidadesCv = pkHabilidadesCv;
    }
    public Cv getCv() {
        return this.cv;
    }
    
    public void setCv(Cv cv) {
        this.cv = cv;
    }
    public CatalogoHabilidad getCatalogoHabilidad() {
        return this.catalogoHabilidad;
    }
    
    public void setCatalogoHabilidad(CatalogoHabilidad catalogoHabilidad) {
        this.catalogoHabilidad = catalogoHabilidad;
    }




}


