package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * HabilidadOferta generated by hbm2java
 */
public class HabilidadOferta  implements java.io.Serializable {


     private BigDecimal pkHabilidadOferta;
     private CatalogoHabilidad catalogoHabilidad;
     private Oferta oferta;

    public HabilidadOferta() {
    }

    public HabilidadOferta(BigDecimal pkHabilidadOferta, CatalogoHabilidad catalogoHabilidad, Oferta oferta) {
       this.pkHabilidadOferta = pkHabilidadOferta;
       this.catalogoHabilidad = catalogoHabilidad;
       this.oferta = oferta;
    }
   
    public BigDecimal getPkHabilidadOferta() {
        return this.pkHabilidadOferta;
    }
    
    public void setPkHabilidadOferta(BigDecimal pkHabilidadOferta) {
        this.pkHabilidadOferta = pkHabilidadOferta;
    }
    public CatalogoHabilidad getCatalogoHabilidad() {
        return this.catalogoHabilidad;
    }
    
    public void setCatalogoHabilidad(CatalogoHabilidad catalogoHabilidad) {
        this.catalogoHabilidad = catalogoHabilidad;
    }
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }




}


