package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * HabilidadLinguisticaCv generated by hbm2java
 */
public class HabilidadLinguisticaCv  implements java.io.Serializable {


     private BigDecimal pkHabLingCv;
     private Cv cv;
     private CatalogoIdioma catalogoIdioma;
     private CatalogoPonderacion catalogoPonderacion;
     private BigDecimal pondConversacionCv;
     private BigDecimal pondEscuchaCv;
     private BigDecimal pondEscritoCv;
     private BigDecimal pondLecturaCv;

    public HabilidadLinguisticaCv() {
    }

    public HabilidadLinguisticaCv(BigDecimal pkHabLingCv, Cv cv, CatalogoIdioma catalogoIdioma, CatalogoPonderacion catalogoPonderacion, BigDecimal pondConversacionCv, BigDecimal pondEscuchaCv, BigDecimal pondEscritoCv, BigDecimal pondLecturaCv) {
       this.pkHabLingCv = pkHabLingCv;
       this.cv = cv;
       this.catalogoIdioma = catalogoIdioma;
       this.catalogoPonderacion = catalogoPonderacion;
       this.pondConversacionCv = pondConversacionCv;
       this.pondEscuchaCv = pondEscuchaCv;
       this.pondEscritoCv = pondEscritoCv;
       this.pondLecturaCv = pondLecturaCv;
    }
   
    public BigDecimal getPkHabLingCv() {
        return this.pkHabLingCv;
    }
    
    public void setPkHabLingCv(BigDecimal pkHabLingCv) {
        this.pkHabLingCv = pkHabLingCv;
    }
    public Cv getCv() {
        return this.cv;
    }
    
    public void setCv(Cv cv) {
        this.cv = cv;
    }
    public CatalogoIdioma getCatalogoIdioma() {
        return this.catalogoIdioma;
    }
    
    public void setCatalogoIdioma(CatalogoIdioma catalogoIdioma) {
        this.catalogoIdioma = catalogoIdioma;
    }
    public CatalogoPonderacion getCatalogoPonderacion() {
        return this.catalogoPonderacion;
    }
    
    public void setCatalogoPonderacion(CatalogoPonderacion catalogoPonderacion) {
        this.catalogoPonderacion = catalogoPonderacion;
    }
    public BigDecimal getPondConversacionCv() {
        return this.pondConversacionCv;
    }
    
    public void setPondConversacionCv(BigDecimal pondConversacionCv) {
        this.pondConversacionCv = pondConversacionCv;
    }
    public BigDecimal getPondEscuchaCv() {
        return this.pondEscuchaCv;
    }
    
    public void setPondEscuchaCv(BigDecimal pondEscuchaCv) {
        this.pondEscuchaCv = pondEscuchaCv;
    }
    public BigDecimal getPondEscritoCv() {
        return this.pondEscritoCv;
    }
    
    public void setPondEscritoCv(BigDecimal pondEscritoCv) {
        this.pondEscritoCv = pondEscritoCv;
    }
    public BigDecimal getPondLecturaCv() {
        return this.pondLecturaCv;
    }
    
    public void setPondLecturaCv(BigDecimal pondLecturaCv) {
        this.pondLecturaCv = pondLecturaCv;
    }




}


