package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LicenciaOferta generated by hbm2java
 */
public class LicenciaOferta  implements java.io.Serializable {


     private BigDecimal pkLicenciaOferta;
     private CatalogoLicencia catalogoLicencia;
     private Oferta oferta;

    public LicenciaOferta() {
    }

    public LicenciaOferta(BigDecimal pkLicenciaOferta, CatalogoLicencia catalogoLicencia, Oferta oferta) {
       this.pkLicenciaOferta = pkLicenciaOferta;
       this.catalogoLicencia = catalogoLicencia;
       this.oferta = oferta;
    }
   
    public BigDecimal getPkLicenciaOferta() {
        return this.pkLicenciaOferta;
    }
    
    public void setPkLicenciaOferta(BigDecimal pkLicenciaOferta) {
        this.pkLicenciaOferta = pkLicenciaOferta;
    }
    public CatalogoLicencia getCatalogoLicencia() {
        return this.catalogoLicencia;
    }
    
    public void setCatalogoLicencia(CatalogoLicencia catalogoLicencia) {
        this.catalogoLicencia = catalogoLicencia;
    }
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }




}


