package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * LicenciaCandidato generated by hbm2java
 */
public class LicenciaCandidato  implements java.io.Serializable {


     private BigDecimal pkLicenciaCandidato;
     private Cv cv;
     private CatalogoLicencia catalogoLicencia;
     private BigDecimal pkCandidato;

    public LicenciaCandidato() {
    }

	
    public LicenciaCandidato(BigDecimal pkLicenciaCandidato, CatalogoLicencia catalogoLicencia, BigDecimal pkCandidato) {
        this.pkLicenciaCandidato = pkLicenciaCandidato;
        this.catalogoLicencia = catalogoLicencia;
        this.pkCandidato = pkCandidato;
    }
    public LicenciaCandidato(BigDecimal pkLicenciaCandidato, Cv cv, CatalogoLicencia catalogoLicencia, BigDecimal pkCandidato) {
       this.pkLicenciaCandidato = pkLicenciaCandidato;
       this.cv = cv;
       this.catalogoLicencia = catalogoLicencia;
       this.pkCandidato = pkCandidato;
    }
   
    public BigDecimal getPkLicenciaCandidato() {
        return this.pkLicenciaCandidato;
    }
    
    public void setPkLicenciaCandidato(BigDecimal pkLicenciaCandidato) {
        this.pkLicenciaCandidato = pkLicenciaCandidato;
    }
    public Cv getCv() {
        return this.cv;
    }
    
    public void setCv(Cv cv) {
        this.cv = cv;
    }
    public CatalogoLicencia getCatalogoLicencia() {
        return this.catalogoLicencia;
    }
    
    public void setCatalogoLicencia(CatalogoLicencia catalogoLicencia) {
        this.catalogoLicencia = catalogoLicencia;
    }
    public BigDecimal getPkCandidato() {
        return this.pkCandidato;
    }
    
    public void setPkCandidato(BigDecimal pkCandidato) {
        this.pkCandidato = pkCandidato;
    }




}


