package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Logro generated by hbm2java
 */
public class Logro  implements java.io.Serializable {


     private BigDecimal pkLogro;
     private Cv cv;
     private String nombreLogro;
     private Date fechaLogro;
     private String descripcionLogro;

    public Logro() {
    }

    public Logro(BigDecimal pkLogro, Cv cv, String nombreLogro, Date fechaLogro, String descripcionLogro) {
       this.pkLogro = pkLogro;
       this.cv = cv;
       this.nombreLogro = nombreLogro;
       this.fechaLogro = fechaLogro;
       this.descripcionLogro = descripcionLogro;
    }
   
    public BigDecimal getPkLogro() {
        return this.pkLogro;
    }
    
    public void setPkLogro(BigDecimal pkLogro) {
        this.pkLogro = pkLogro;
    }
    public Cv getCv() {
        return this.cv;
    }
    
    public void setCv(Cv cv) {
        this.cv = cv;
    }
    public String getNombreLogro() {
        return this.nombreLogro;
    }
    
    public void setNombreLogro(String nombreLogro) {
        this.nombreLogro = nombreLogro;
    }
    public Date getFechaLogro() {
        return this.fechaLogro;
    }
    
    public void setFechaLogro(Date fechaLogro) {
        this.fechaLogro = fechaLogro;
    }
    public String getDescripcionLogro() {
        return this.descripcionLogro;
    }
    
    public void setDescripcionLogro(String descripcionLogro) {
        this.descripcionLogro = descripcionLogro;
    }




}


