package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private BigDecimal pkMenu;
     private String menu;
     private Set<Submenu> submenus = new HashSet<Submenu>(0);

    public Menu() {
    }

	
    public Menu(BigDecimal pkMenu, String menu) {
        this.pkMenu = pkMenu;
        this.menu = menu;
    }
    public Menu(BigDecimal pkMenu, String menu, Set<Submenu> submenus) {
       this.pkMenu = pkMenu;
       this.menu = menu;
       this.submenus = submenus;
    }
   
    public BigDecimal getPkMenu() {
        return this.pkMenu;
    }
    
    public void setPkMenu(BigDecimal pkMenu) {
        this.pkMenu = pkMenu;
    }
    public String getMenu() {
        return this.menu;
    }
    
    public void setMenu(String menu) {
        this.menu = menu;
    }
    public Set<Submenu> getSubmenus() {
        return this.submenus;
    }
    
    public void setSubmenus(Set<Submenu> submenus) {
        this.submenus = submenus;
    }




}


