package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private BigDecimal pkMunicipio;
     private Departamento departamento;
     private String nombreMunicipio;
     private Set<Oferta> ofertas = new HashSet<Oferta>(0);
     private Set<Empresa> empresas = new HashSet<Empresa>(0);
     private Set<Candidato> candidatos = new HashSet<Candidato>(0);

    public Municipio() {
    }

	
    public Municipio(BigDecimal pkMunicipio, String nombreMunicipio) {
        this.pkMunicipio = pkMunicipio;
        this.nombreMunicipio = nombreMunicipio;
    }
    public Municipio(BigDecimal pkMunicipio, Departamento departamento, String nombreMunicipio, Set<Oferta> ofertas, Set<Empresa> empresas, Set<Candidato> candidatos) {
       this.pkMunicipio = pkMunicipio;
       this.departamento = departamento;
       this.nombreMunicipio = nombreMunicipio;
       this.ofertas = ofertas;
       this.empresas = empresas;
       this.candidatos = candidatos;
    }
   
    public BigDecimal getPkMunicipio() {
        return this.pkMunicipio;
    }
    
    public void setPkMunicipio(BigDecimal pkMunicipio) {
        this.pkMunicipio = pkMunicipio;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombreMunicipio() {
        return this.nombreMunicipio;
    }
    
    public void setNombreMunicipio(String nombreMunicipio) {
        this.nombreMunicipio = nombreMunicipio;
    }
    public Set<Oferta> getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Set<Oferta> ofertas) {
        this.ofertas = ofertas;
    }
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }
    public Set<Candidato> getCandidatos() {
        return this.candidatos;
    }
    
    public void setCandidatos(Set<Candidato> candidatos) {
        this.candidatos = candidatos;
    }




}


