package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private BigDecimal pkUsuario;
     private Empresa empresa;
     private Candidato candidato;
     private Rol rol;
     private String usuario;
     private String contrasena;
     private String correoElectronico;
     private BigDecimal tipoPerfil;

    public Perfil() {
    }

	
    public Perfil(BigDecimal pkUsuario, Rol rol, String usuario, String contrasena, String correoElectronico, BigDecimal tipoPerfil) {
        this.pkUsuario = pkUsuario;
        this.rol = rol;
        this.usuario = usuario;
        this.contrasena = contrasena;
        this.correoElectronico = correoElectronico;
        this.tipoPerfil = tipoPerfil;
    }
    public Perfil(BigDecimal pkUsuario, Empresa empresa, Candidato candidato, Rol rol, String usuario, String contrasena, String correoElectronico, BigDecimal tipoPerfil) {
       this.pkUsuario = pkUsuario;
       this.empresa = empresa;
       this.candidato = candidato;
       this.rol = rol;
       this.usuario = usuario;
       this.contrasena = contrasena;
       this.correoElectronico = correoElectronico;
       this.tipoPerfil = tipoPerfil;
    }
   
    public BigDecimal getPkUsuario() {
        return this.pkUsuario;
    }
    
    public void setPkUsuario(BigDecimal pkUsuario) {
        this.pkUsuario = pkUsuario;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public BigDecimal getTipoPerfil() {
        return this.tipoPerfil;
    }
    
    public void setTipoPerfil(BigDecimal tipoPerfil) {
        this.tipoPerfil = tipoPerfil;
    }




}


