package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Postulacion generated by hbm2java
 */
public class Postulacion  implements java.io.Serializable {


     private BigDecimal pkPostulacion;
     private Cv cv;
     private Oferta oferta;
     private byte porcentajeAcoplamiento;

    public Postulacion() {
    }

    public Postulacion(BigDecimal pkPostulacion, Cv cv, Oferta oferta, byte porcentajeAcoplamiento) {
       this.pkPostulacion = pkPostulacion;
       this.cv = cv;
       this.oferta = oferta;
       this.porcentajeAcoplamiento = porcentajeAcoplamiento;
    }
   
    public BigDecimal getPkPostulacion() {
        return this.pkPostulacion;
    }
    
    public void setPkPostulacion(BigDecimal pkPostulacion) {
        this.pkPostulacion = pkPostulacion;
    }
    public Cv getCv() {
        return this.cv;
    }
    
    public void setCv(Cv cv) {
        this.cv = cv;
    }
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }
    public byte getPorcentajeAcoplamiento() {
        return this.porcentajeAcoplamiento;
    }
    
    public void setPorcentajeAcoplamiento(byte porcentajeAcoplamiento) {
        this.porcentajeAcoplamiento = porcentajeAcoplamiento;
    }




}


