package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Resultado generated by hbm2java
 */
public class Resultado  implements java.io.Serializable {


     private BigDecimal pkResultado;
     private Prueba prueba;
     private String resultado;

    public Resultado() {
    }

    public Resultado(BigDecimal pkResultado, Prueba prueba, String resultado) {
       this.pkResultado = pkResultado;
       this.prueba = prueba;
       this.resultado = resultado;
    }
   
    public BigDecimal getPkResultado() {
        return this.pkResultado;
    }
    
    public void setPkResultado(BigDecimal pkResultado) {
        this.pkResultado = pkResultado;
    }
    public Prueba getPrueba() {
        return this.prueba;
    }
    
    public void setPrueba(Prueba prueba) {
        this.prueba = prueba;
    }
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }




}


