package com.bad.sbtel;
// Generated 05-11-2019 11:29:44 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private BigDecimal pkRol;
     private String nombreRol;
     private Set<Perfil> perfils = new HashSet<Perfil>(0);
     private Set<RolSubmenu> rolSubmenus = new HashSet<RolSubmenu>(0);

    public Rol() {
    }

	
    public Rol(BigDecimal pkRol, String nombreRol) {
        this.pkRol = pkRol;
        this.nombreRol = nombreRol;
    }
    public Rol(BigDecimal pkRol, String nombreRol, Set<Perfil> perfils, Set<RolSubmenu> rolSubmenus) {
       this.pkRol = pkRol;
       this.nombreRol = nombreRol;
       this.perfils = perfils;
       this.rolSubmenus = rolSubmenus;
    }
   
    public BigDecimal getPkRol() {
        return this.pkRol;
    }
    
    public void setPkRol(BigDecimal pkRol) {
        this.pkRol = pkRol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Set<Perfil> getPerfils() {
        return this.perfils;
    }
    
    public void setPerfils(Set<Perfil> perfils) {
        this.perfils = perfils;
    }
    public Set<RolSubmenu> getRolSubmenus() {
        return this.rolSubmenus;
    }
    
    public void setRolSubmenus(Set<RolSubmenu> rolSubmenus) {
        this.rolSubmenus = rolSubmenus;
    }




}


